// http:thor-project-wks5-8.herokuapp.com/ tests

### Create a card

POST https://thor-project-wks5-8.herokuapp.com/cards HTTP/1.1
Content-Type: application/json

{
  "title": "Validation Card",
  "description": "The validation test card for my project management tool.",
  "startDate": "2022-05-28",
  "dueDate": "2022-06-22",
  "assignedTo": "Thor",
  "isDone":false,
  "isBlocked":true
}

### Get all cards

GET https://thor-project-wks5-8.herokuapp.com/cards

### Get one card by ID

GET https://thor-project-wks5-8.herokuapp.com/cards/628ae9c3eaedf5771995e3c7

### Update a card

PUT https://thor-project-wks5-8.herokuapp.com/cards/628914a5379a7cdd86ad7df1 HTTP/1.1
Content-Type: application/json

{
  "title": "Test Update Card",
  "description": "The updated test card for my project management tool.",
  "startDate": "2022-05-22",
  "dueDate": "2022-06-22",
  "assignedTo": "Thor",
  "isDone":false,
  "isBlocked":true
}

### Delete card by ID

DELETE https://thor-project-wks5-8.herokuapp.com/cards/628914a5379a7cdd86ad7df1

### Create a comment

POST https://thor-project-wks5-8.herokuapp.com/comments HTTP/1.1
Content-Type: application/json

{
  "comment": "Test comment after many fails",
  "cardId": "6288fce039bcb2bd2bf3d121",
  "user": "Thor",
  "dateAdded": "2022-05-27"
}

### Get all comments by card ID

GET https://thor-project-wks5-8.herokuapp.com/comments/6288fce039bcb2bd2bf3d121

### Update comment by ID

PUT https://thor-project-wks5-8.herokuapp.com/comments/628d8d388948684405d3c135 HTTP/1.1
Content-Type: application/json

{
  "comment": "I'm changing this comment and adding and update date",
  "dateModified": "2022-05-24"
}

### Delete a comment

DELETE https://thor-project-wks5-8.herokuapp.com/comments/628d98e6028e105a1bf73ab3

### Create a user:

POST https://thor-project-wks5-8.herokuapp.com/users HTTP/1.1
Content-Type: application/json

{
  "email": "stevie@me.com",
  "firstName": "Steve",
  "lastName": "Stevens"
}

### Get a user by email 

GET https://thor-project-wks5-8.herokuapp.com/users/stevie@me.com

### Delete a user by email

DELETE https://thor-project-wks5-8.herokuapp.com/users/stevie@me.com

// Negative tests

### Create a card no title

POST https://thor-project-wks5-8.herokuapp.com/cards HTTP/1.1
Content-Type: application/json

{
  "title": "",
  "description": "The validation test card for my project management tool.",
  "startDate": "2022-05-28",
  "dueDate": "2022-06-22",
  "assignedTo": "Thor",
  "isDone":false,
  "isBlocked":true
}
//Should return error

### Create a card no description

POST https://thor-project-wks5-8.herokuapp.com/cards HTTP/1.1
Content-Type: application/json

{
  "title": "Validation Card",
  "description": "",
  "startDate": "2022-05-28",
  "dueDate": "2022-06-22",
  "assignedTo": "Thor",
  "isDone":false,
  "isBlocked":true
}
//Should return error

### Create a card no title & no description

POST https://thor-project-wks5-8.herokuapp.com/cards HTTP/1.1
Content-Type: application/json

{
  "title": "",
  "description": "",
  "startDate": "2022-05-28",
  "dueDate": "2022-06-22",
  "assignedTo": "Thor",
  "isDone":false,
  "isBlocked":true
}
//Should return error

### Create a card no dates, assigned to, isdone, and isblocked
POST https://thor-project-wks5-8.herokuapp.com/cards HTTP/1.1
Content-Type: application/json

{
  "title": "Dates test",
  "description": "This card should be created without dates, which are not required",
  "startDate": "",
  "dueDate": "",
  "assignedTo": ""
}
//Should create card with blank dates and default booleans

### Comments missing 

POST  https://thor-project-wks5-8.herokuapp.com/comments/ HTTP/1.1
Content-Type: application/json

{
  "cardId": "6288fce039bcb2bd2bf3d121",
  "user": "Thor",
  "dateAdded": "2022-05-27"
}

### cardId missing

POST  https://thor-project-wks5-8.herokuapp.com/comments/ HTTP/1.1
Content-Type: application/json

{
  "comment": "Test input comment",
  "user": "Thor",
  "dateAdded": "2022-05-27"
}

// User controller testing

### Input user info

POST https://thor-project-wks5-8.herokuapp.com/users HTTP/1.1
Content-Type: application/json

{
  "email": "thor@larsen.com",
  "firstName": "Thor",
  "lastName": "Larsen"
}

### Test user info

POST https://thor-project-wks5-8.herokuapp.com/users HTTP/1.1
Content-Type: application/json

{
  "email": "thorlarsen.com",
  "firstName": "Thor",
  "lastName": "Larsen"
}
