// http:localhost:3000/ tests

### Create a card

POST http://localhost:8080/cards HTTP/1.1
Content-Type: application/json

{
  "title": "First Card",
  "description": "The first card for my project management tool.",
  "startDate": "05-20-2022",
  "dueDate": "06-20-2022",
  "assignedTo": "Thor",
  "isDone": "false",
  "isBlocked": "false"
}

### Get all cards

GET http://localhost:8080/cards
